# Minimum GitHub Actions configuration
name: Sharing Session
on: [push]
env: # env variable for fetch our GitHub Actions secrets
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
jobs:
  test:
    name: Test SSH Connection to My VM
    runs-on: ubuntu-latest # use GitHub shared runner
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.SSH_PRIVATE_KEY }}
          known_hosts: ${{ env.SSH_KNOWN_HOSTS }}
      - run: echo "Sharing session!"
      - run: whoami
      - run: pwd
      - run: ssh deploy@sharing-session.itsgitz.my.id "lsb_release -a"

  upload:
    needs: [test]
    name: Upload my website to my server
    runs-on: ubuntu-latest
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.SSH_PRIVATE_KEY }}
          known_hosts: ${{ env.SSH_KNOWN_HOSTS }} 
      - uses: actions/checkout@v3
      - run: ssh deploy@sharing-session.itsgitz.my.id "sudo chmod 777 -Rf /var/www/html/" 
      - run: rsync -arp index.html deploy@sharing-session.itsgitz.my.id:/var/www/html/
      - run: ssh deploy@sharing-session.itsgitz.my.id "sudo nginx -t" 
      - run: ssh deploy@sharing-session.itsgitz.my.id "sudo systemctl restart nginx"
